### PR TITLE
Inverse design

### PR DESCRIPTION
**Pull request by dakotaramos**
Delete the text explanations below these headers and replace them with information about your PR.
Please first consult the [developer guide](https://weis.readthedocs.io/en/latest/how_to_contribute_code.html) to make sure your PR follows all code, testing, and documentation conventions.

## Purpose
Sandbox for us to resolve the floating platform cost computations
@gbarter please feel free to add on what we discussed on the call and reach out with any questions.
## Type of change

- [ x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by gbarter** [comment]
I assume this is the PR that I should make changes to?

@johnjasa, Any tips or links about how I edit the PR locally would be welcome

**Comment by gbarter** [comment]
@dakotaramos hold off on further commits for this.  I am prepping a WISDEM PR that addresses your needs.

**Comment by dakotaramos** [comment]
@gbarter sorry about that! I was trying to push up some work John and I did today. I didn't realize it would impact this PR

**Comment by gbarter** [comment]
@dakotaramos Check out this WISDEM PR to make sure if has all of the changes you need:
https://github.com/WISDEM/WISDEM/pull/308

If it looks good, I will subtree it in here.  The tedious part of WEIS is that if you need changes in WISDEM code, that has to be done with a WISDEM PR and then brought into WEIS separately.

**Review by johnjasa — APPROVED** [review]
This looks good on my end and is ready to merge in! @gbarter, as you marked yourself as a reviewer I'll let you approve and merge as you see fit.

**Pull request merged**
