### PR TITLE
Mac compilation

### PR DESCRIPTION
**Pull request by dzalkind**
## Purpose
Fix and test compilation on mac

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by dzalkind** [comment]
Now I'm quite confused because the first commit in this PR was supposed to fail.  It looks like it's building fine in mac on the CI after all, unless my tests are not catching the failure.

**Comment by gbarter** [comment]
Not sure what the intended failure was- you are using conda and homebrew compilers together?  Conda sets a number of environment variables with the install of the compilers that might overwrite any prior setting of FC environment variables

**Comment by dzalkind** [comment]
In that first commit, I was only using conda compilers, and I thought we just weren't catching the errors that occurred when compiling some of the libraries.  This makes it seem like it's compiling fine with only conda compilers on mac, which doesn't agree with what we've seen locally.

**Comment by gbarter** [comment]
We have mixed results locally.  My computer does fine with conda compilers.  Pietro not so much.

**Comment by gbarter** [comment]
This is resolved in Pietro's PR.  I think we can close it.

**Pull request closed without merging**
