### PR TITLE
Level 1 Control

### PR DESCRIPTION
**Pull request by dzalkind**
## Purpose
Pass ROSCO control gains to other levels of WEIS, in this case Level1/RAFT.

Other changes:
- Update ROSCO_toolbox subtree

This PR might break the RAFT subtree. I can revert that part, or we may end up re-adding that subtree later.  It is part of a RAFT branch that might be a ways off still: https://github.com/WISDEM/RAFT/blob/40bbd5e4f1bf5d7e8647140d5f9d4a2dee6561aa/raft/omdao_raft.py#L87

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Run example `examples/03_NREL5MW_OC3_spar/weis_freq_driver.py` and see pitch control gains in `RAFT/raft/omdao_raft.py`. 

## Checklist
_Put an `x` in the boxes that apply._

- [ x] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by ptrbortolotti — APPROVED** [review]
Looks good to me! Just a heads up for everybody that the API (modeling options) is changing here

**Comment by dzalkind** [comment]
Ah, good point. I updated the modeling options dicts in the code, but not in the examples.  I can do that.  Tests still passed with ROSCO being a level 3 option though...

**Comment by ptrbortolotti** [comment]
WEIS tests are benevolent...

**Review by gbarter — COMMENTED** [review]
Is the change to `omdao_raft.py` also made in the parent RAFT repo?  I don't see any PRs there. . .

**Review by gbarter — APPROVED** [review]

**Review by nikhar-abbas — APPROVED** [review]
Looks good to me!

**Review by johnjasa — APPROVED** [review]

**Pull request merged**
