### PR TITLE
Fix connections to drivese_post with WISDEM 3.17

### PR DESCRIPTION
**Pull request by dzalkind**
## Purpose
The WISDEM 3.17 release changed a few of the WEIS connections:  
https://github.com/WISDEM/WISDEM/commit/87d973e91b718fae4c8bdae4c8033ff21e6e50bc#diff-29b1e9d8ea97d386866e2c69eedbfc27df5594cd8f888e8884f5a37aeb694e2fL55

This PR will get things working, but I have questions about the connection.

The change seems to indicate that the connection from WEIS should not include the weight of the rotor in the connection from OpenFAST to the drivese load.  Am I interpreting this correctly?  Should the output from aeroelasticse be adapted?

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by gbarter** [comment]
This is a good point.  The fix in WISDEM was a clear bug (PR [here](https://github.com/WISDEM/WISDEM/pull/558/files) if it helps).  Maybe the drivese code should have a flag instead about whether the F/M_hub contains the weight as well?  That way it will be set one way for internal WISDEM calcs and another way for fielding OpenFAST load results?

**Comment by dzalkind** [comment]
Thanks @gbarter!  I believe we can get the aero-only load from OpenFAST/WEIS and make sure that is what's connected to WISDEM.  Would that be a correct solution?

**Comment by gbarter** [comment]
> Thanks @gbarter! I believe we can get the aero-only load from OpenFAST/WEIS and make sure that is what's connected to WISDEM. Would that be a correct solution?

Yes!  That would make things easy for sure

**Comment by dzalkind** [comment]
I think the connections for the aero-only hub loads have been fixed.  

@gbarter, I found an openfast error that looks like an issue with the mode identification in this example: https://github.com/WISDEM/WEIS/blob/wisdem_317/examples/03_NREL5MW_OC3_spar/weis_driver.py

It looks like the 1st and 2nd fore-aft mode shapes are the same. 
```
---------------------- TOWER FORE-AFT MODE SHAPES ------------------------------
0.9729651245822929     TwFAM1Sh(2) - Mode 1, coefficient of x^2 term
0.15807511001173988    TwFAM1Sh(3) -       , coefficient of x^3 term
-0.11804612691480079   TwFAM1Sh(4) -       , coefficient of x^4 term
0.09735014728827093    TwFAM1Sh(5) -       , coefficient of x^5 term
-0.11034425496750294   TwFAM1Sh(6) -       , coefficient of x^6 term
0.9725681765621477     TwFAM2Sh(2) - Mode 2, coefficient of x^2 term
0.15830548941131528    TwFAM2Sh(3) -       , coefficient of x^3 term
-0.1181006738478321    TwFAM2Sh(4) -       , coefficient of x^4 term
0.09772605127408993    TwFAM2Sh(5) -       , coefficient of x^5 term
-0.1104990433997208    TwFAM2Sh(6) -       , coefficient of x^6 term
```

**Comment by gbarter** [comment]
> I think the connections for the aero-only hub loads have been fixed.
> 
> @gbarter, I found an openfast error that looks like an issue with the mode identification in this example: https://github.com/WISDEM/WEIS/blob/wisdem_317/examples/03_NREL5MW_OC3_spar/weis_driver.py
> 
> It looks like the 1st and 2nd fore-aft mode shapes are the same.
> 
> ```
> ---------------------- TOWER FORE-AFT MODE SHAPES ------------------------------
> 0.9729651245822929     TwFAM1Sh(2) - Mode 1, coefficient of x^2 term
> 0.15807511001173988    TwFAM1Sh(3) -       , coefficient of x^3 term
> -0.11804612691480079   TwFAM1Sh(4) -       , coefficient of x^4 term
> 0.09735014728827093    TwFAM1Sh(5) -       , coefficient of x^5 term
> -0.11034425496750294   TwFAM1Sh(6) -       , coefficient of x^6 term
> 0.9725681765621477     TwFAM2Sh(2) - Mode 2, coefficient of x^2 term
> 0.15830548941131528    TwFAM2Sh(3) -       , coefficient of x^3 term
> -0.1181006738478321    TwFAM2Sh(4) -       , coefficient of x^4 term
> 0.09772605127408993    TwFAM2Sh(5) -       , coefficient of x^5 term
> -0.1104990433997208    TwFAM2Sh(6) -       , coefficient of x^6 term
> ```

I'm not seeing that error locally in the example you mentioned and it seems like the CI tests are failing on a different example (`06/weis_driver_monopile.py`).  Would you like me to help debug that failure?

**Pull request merged**
