### PR TITLE
Clean aeroelasticse

### PR DESCRIPTION
**Pull request by ptrbortolotti**
This PR takes a first pass at cleaning aeroelasticse by 
* removing legacy code
* stopping support for fastv7, fastv8, and aerodyn14
* adding new tests
* streamline dependencies

## Purpose
Increase the coverage of aeroleasticse and prepare the ground for the global DLC driver

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Testing
A couple more tests were added
* fast reader and writer
* turbsim reader and writer
* turbsim standalone driver

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run existing tests which pass locally with my changes
- [x] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by gbarter — APPROVED** [review]
This is already a lot of work- thank you!

**Review by dzalkind — APPROVED** [review]
Looks good!

**Review by nikhar-abbas — APPROVED** [review]
I was able to run my current large-scale optimization scripts with this, nice work Pietro!

**Review by johnjasa — APPROVED** [review]

**Comment by ptrbortolotti** [comment]
thank you all, my next PR will be about the global DLC driver

**Pull request merged**
