### PR TITLE
Python interface bugfix

### PR DESCRIPTION
**Pull request by rafmudaf**
## Purpose
This pull request updates the included OpenFAST repo to add a fix for bugs in the Python interface. It should allow for WEIS to run OpenFAST simulations with output data passed back to the calling routines in-memory.

TODO:

- [ ] Update the OpenFAST input files generated by WEIS to OpenFAST v3.0 format

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
To test whether this code works, first the OpenFAST input files generated by WEIS must be updated to OpenFAST v3.0 format. Then, I modified `runFAST_pywrapper.py` forcing it to use the OpenFAST Python interface.

Since I have not yet completed updating the OpenFAST input files, this has not been fully tested.

## Checklist
- [ ] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by gbarter** [comment]
@rafmudaf Thank you for this!  We will get going on modifying the OpenFAST input file writers to be 3.0 compliant and also updating the existing input decks.

**Comment by rafmudaf** [comment]
No problem @gbarter. I have started to modify the input file generation routines in WEIS, and I'll continue to add it here as I work on it.

**Comment by gbarter** [comment]
@ptrbortolotti is already in the midst of a big AeroelasticSE cleanup on the global_dlc_driver branch.  It might be good to merge those changes into this branch first.  I'll let Pietro weigh in.

**Comment by nikhar-abbas** [comment]
> @rafmudaf Thank you for this! We will get going on modifying the OpenFAST input file writers to be 3.0 compliant and also updating the existing input decks.

If it helps out, I recently made some updates to the FAST_reader and FAST_writer in the ROSCO toolbox for OF v3.0:
https://github.com/NREL/ROSCO_toolbox/commit/cdc2075665dd77ee14c1d2d413c8d84c0c0d6055

**Comment by dzalkind** [comment]
I just pushed some changes to run the openfast library using [this test](https://github.com/WISDEM/WEIS/blob/master/weis/test/test_aeroelasticse/test_DLC.py). The test failed because it's a regression test that might need to be updated. I had to mess with `runFAST_pywrapper`, so maybe check me there.

**Comment by gbarter** [comment]
I'm not enough of a Github jockey to be able to contribute to Raf's fork to help resolve the OF 3.0 update issues.  I'm going to redirect this PR into a local branch so that I can more easily contribute.

**Pull request merged**
