### PR TITLE
Linear Turbine Models

### PR DESCRIPTION
**Pull request by dzalkind**
I am adding linearization tools to WEIS, including generating linear models using aeroelasticse, setting up linear turbine model objects using mbc3, and simulating a linear turbine in an example script.

Major Changes:
- Added mbc3 tools to generate linear time invariant models of a turbine
- Added LinearFAST.py to aeroelasticse for generating linear models
- Added LinearModel.py to weis/control for setting up linear turbine and control models

Minor Changes:
- I needed to make a minor change to the ROSCO_Toolbox that will be pulled in #16.  There is a small change in a pCrunch example that excludes MoorDyn outputs from the output file processing list. 
- Some other related example scripts were included: run_PC_sweep.py and run_mass_sweep.py for varying control and model parameters for an initial CCD problem demo
- Ignoring output files from WEIS.  Are these needed for testing purposes and we should be saving results elsewhere?

TODO:
- We may need to update `setup.py` because there is an additional python dependency to include: control

Scripts to test:
1. LinearFAST.py in WEIS/aeroelasticse/
2. run_lin_turbine.py in WEIS/examples/control_opt/

### CODE REVIEW

**Review by johnjasa — COMMENTED** [review]
Thanks for this, @dzalkind. I'm working on running the examples locally now.

Does it make sense to add the examples you created to the [automated testing platform here](https://github.com/WISDEM/WEIS/blob/develop/.github/workflows/CI_WEIS.yml)? If they don't take too long to run (<10 mins each), it'd be good to have this functionality tested. Or, if there's some way to shorten the run time for those examples so they could be more easily tested, I welcome that. If you think it's possible to have those examples be run as part of the CI, please add those calls into the `CI_WEIS.yml`.

**Comment by gbarter** [comment]
Instead of adding custom code and runs to the CI script with each addition, maybe we create a separate pytest-like call to a dedicated examples directory?  Could use the [test_examples.py template in WISDEM](https://github.com/WISDEM/WISDEM/blob/develop/wisdem/test/test_examples/test_examples.py) if that is helpful.

**Comment by johnjasa** [comment]
Great idea, Garrett! I'll work to get something like that here for WEIS and will submit my own PR.

**Comment by dzalkind** [comment]
The examples `run_PC_sweep.py` and `run_mass_sweep.py` are probably more examples of things we can do with aeroelasticse than good tests.  I don't think they cover any more code than `run_DLC.py` does and they take longer than ~10 mins, so we could exclude them or move them out of examples.  `run_lin_turbine.py` does cover the new things I've added in this PR.

**Pull request merged**
