### PR TITLE
F/update dac

### PR DESCRIPTION
**Pull request by ptrbortolotti**
Update the DAC example, which is currently not part of GitHub Actions (because it calls XFoil)
This process highlighted:
1) a bug in the glue code in the call to landbosse
2) a bug from a legacy code with the old version of drivese
3) the need to include IPC_Ki1p and the rotor overspeed among the default values of analysis option.yaml

### CODE REVIEW

**Review by johnjasa — APPROVED** [review]
Thanks for these updates, Pietro. To be clear, we're still not testing the DAC directly due to the usage of XFoil, correct?

**Comment by ptrbortolotti** [comment]
Correct. XFoil is not easily installable on GitHub Actions (as far as I understand), and this script needs it...

**Comment by nikhar-abbas** [comment]
I was able to successfully run dac_driver.py on eagle, so looks good to me! @johnjasa, I think you can merge this when you feel good about it.

**Comment by johnjasa** [comment]
Great, thanks for checking that out! I'll wait for the rest of the CI to finish, just in case, then will merge it.

**Comment by johnjasa** [comment]
@ptrbortolotti, looks like the `control_opt` example fails with that schema change for `rotor_overspeed`, could you check it out?

**Comment by ptrbortolotti** [comment]
@nikhar-abbas @dzalkind 
I am not familiar with the optimization of the rotor overspeed. The error here is caused by the analysis option schema. This file has a minimum value of -0.05
https://github.com/WISDEM/WEIS/blob/cd5aef5b087ca016c5d098192f3025592985bd5e/examples/control_opt/analysis_options.yaml#L162
But the schema sets a minimum of 0
https://github.com/WISDEM/WEIS/blob/8f9eaa15b0e4787409df9091b34aabb08a0cc9a5/weis/schema/analysis_defaults.yaml#L149
Should I lower the minimum allowable in the schema or increase the minimum value in the yaml file?

**Comment by ptrbortolotti** [comment]
@johnjasa I'm afraid that after the first bug is resolved another will appear. XFoil is not installed, so I'll comment out the DAC portion from the yaml file

**Comment by nikhar-abbas** [comment]
> @nikhar-abbas @dzalkind
> I am not familiar with the optimization of the rotor overspeed. The error here is caused by the analysis option schema. This file has a minimum value of -0.05
> https://github.com/WISDEM/WEIS/blob/cd5aef5b087ca016c5d098192f3025592985bd5e/examples/control_opt/analysis_options.yaml#L162
> 
> 
> But the schema sets a minimum of 0
> https://github.com/WISDEM/WEIS/blob/8f9eaa15b0e4787409df9091b34aabb08a0cc9a5/weis/schema/analysis_defaults.yaml#L149
> 
> 
> Should I lower the minimum allowable in the schema or increase the minimum value in the yaml file?

@ptrbortolotti I'm surprised this slipped through the cracks previously - you can just increases the minimum value in the yaml file to 0.0.

**Review by nikhar-abbas — APPROVED** [review]

**Comment by ptrbortolotti** [comment]
I am not sure why the Ubuntu failed... @gbarter  or @johnjasa ?

**Comment by gbarter** [comment]
Looks a little odd- I clicked on "re-run"

**Pull request merged**
