### PR TITLE
OpenFAST v3.0 update 

### PR DESCRIPTION
**Pull request by gbarter**
## Purpose
Completes the updates to the AeroelasticSE wrappers for OpenFAST v3.0

## Type of change
- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
- [x] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by gbarter** [comment]
@rafmudaf Many thanks for doing 98% of the work here!

**Comment by gbarter** [comment]
@rafmudaf @nikhar-abbas @dzalkind @johnjasa @ptrbortolotti 
Does anyone want to wait before merging this in with `develop`?

**Comment by johnjasa** [comment]
@dzalkind, you would know more on the OF linearization side: should we merge in our PR first, then this one? Or the merge this one, resolve the conflicts, then ours?

**Comment by rafmudaf** [comment]
The Python interface still hasn't been completely tested. The changes to the OoenFAST subtree here shouldn't change anything with running OpenFAST with the executable, but I just wanted to point this out.

**Comment by gbarter** [comment]
I'm seeing some errors in the CI tests that I cannot replicate locally.  I will see what I can do to fix the tests.

@rafmudaf not sure if this error means anything to you regarding the python library access:
```Error 4: b'FAST_InitializeAll:Error allocating ED%Input and ED%InputTimes.'```

**Comment by dzalkind** [comment]
I don't think this is ready.  I think we have fixed the interpolation error in #116 and there are several instances of the OpenFAST python library returning `Error 0: b''` when OpenFAST has an error.  It would be good to know what those errors are like we do when running with the executable.

#116 has fixed a lot of the testing issues and will let us test OpenFAST with the executable for debugging this PR.

**Comment by dzalkind** [comment]
I synced up our merges with `develop` and am happy with where it's at.  I also tested linearization with the OpenFAST python library and it works...thanks @rafmudaf! 

I'm happy to help iron out the examples.

**Pull request merged**
