### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by gbarter**
## Purpose
Fixes at least one of the failed tests and raises an Exception if OpenFAST fails for easier testing.

## Type of change
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
- [x] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by gbarter** [comment]
@rafmudaf : I am changing how errors are handled in the OpenFAST library wrapper by raising Exceptions instead or just printing.  Do you want me to fork and submit a PR to your personal openfast fork? If so, which branch? OpenFAST dev?

**Comment by gbarter** [comment]
@dzalkind : When you get a chance on Monday, I could use your help fixing this test:
https://github.com/WISDEM/WEIS/blob/fix_tests/weis/aeroelasticse/test/test_OF_utils.py#L64

I am getting this error:
```
OpenFAST-v0.1-949-g895ce46d-dirty
 Compile Info:
  - Compiler: GCC version 9.3.0
  - Architecture: 64 bit
  - Precision: single
  - OpenMP: No
  - Date: Jul  9 2021
  - Time: 21:29:32
 Execution Info:
  - Date: 07/09/2021
  - Time: 22:05:52-0600

 OpenFAST input file heading:
     Generated with AeroElasticSE FAST driver

 Running ElastoDyn.
 Nodal outputs section of ElastoDyn input file not found or improperly formatted.
 Running AeroDyn.
 AD15 Nodal Outputs: Nodal output section of AeroDyn input file not found or improperly formatted.
 Skipping nodal outputs.
 Running InflowWind.
 Running ServoDyn.
  Time: 0 of 6 seconds.

 Unable to find steady-state solution.

 OpenFAST encountered an error at simulation time 6 of 6 seconds.
  Simulation error level: FATAL ERROR

  Aborting OpenFAST.
```

**Comment by rafmudaf** [comment]
> @rafmudaf : I am changing how errors are handled in the OpenFAST library wrapper by raising Exceptions instead or just printing. Do you want me to fork and submit a PR to your personal openfast fork? If so, which branch? OpenFAST dev?

Either a pull request to my fork's `feature/python_driver` branch or I can cherry-pick the commits.

**Comment by rafmudaf** [comment]
@gbarter The OpenFAST change is well contained, so I'll just copy it over.

**Comment by gbarter** [comment]
Thank you, Raf!

**Pull request merged**
