### PR TITLE
Updates for TMD and Level 1 RAFT

### PR DESCRIPTION
**Pull request by johnjasa**
## Purpose
Major updates for Level 1 RAFT analysis, TMD optimization, and CCD optimization bugfixes.

I've cleaned up the WISDEM side of things and have a parallel PR in for develop there as well. I think this PR is now ready for further review before merging, pending tests passing.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by gbarter** [comment]
@dzalkind Do we really want to always keep the time histories?  We had set that default to False because it would bog down large parallel runs.  I could also envision that a critical element of co-design requires having that available.

**Comment by dzalkind** [comment]
Yeah, I'd like access to that information by default.  I haven't noticed any performance issues.  I think the timeseries were already being kept at the `runFAST_pywrapper` level, anyway.

**Comment by gbarter** [comment]
This will sound nitpicky when there are so many other development to-do items, but my preference would be to just change the default `keep_time` value to True instead of removing the option all together.  I'm looking mostly at [55c5814](https://github.com/WISDEM/WEIS/pull/162/commits/55c5814ef2a850cda93a3ab5f761fdd92fe8a3d7)

**Comment by gbarter** [comment]
Thanks all 3 of you in getting all of the cases running and tests passing.

@johnjasa - If there are any examples or cases here that need the `rank_and_file` which I've proposed as user option in your WISDEM PR, then we would have to tweak the `modeling_options` files accordingly.

**Review by gbarter — APPROVED** [review]

**Comment by johnjasa** [comment]
#167 contains these changes

**Pull request closed without merging**
