### PR TITLE
bug fix in vizFileGen and changes to handle Jul 2024 Kestrel updates

### PR DESCRIPTION
**Pull request by mayankchetan**
## Purpose
Minor bug fixes for WEIS Viz input generation tool. Changes to kestrel installation script to handle the Jul 2024 Kestrel updates

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Testing
Tested on Kestrel on 01AUG24

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by dzalkind** [comment]
Thanks @mayankchetan! When this is ready, can you assign a reviewer?

**Comment by mayankchetan** [comment]
@sora-ryu Can you review these changes?

@dzalkind, we might have to add @sora-ryu to the repo as a contributor.

**Comment by sora-ryu** [comment]
Hey @mayankchetan ,  the viz file generation works well with raft optimization, but having some error on openfast optimization. Do you want to check on this?

image

**Comment by mayankchetan** [comment]
Can you try again after updating your WEIS env? I think these are recent changes.

**Comment by sora-ryu** [comment]
Hmm, I am having a same error after reinstallation as well.

**Comment by sora-ryu** [comment]
@mayankchetan - I just temporarily changed modeling and geometry input yaml files for now and it works fine. (1. Manually changed the floating platform member types Ca and Cd from singular value to array type. 2. Set path2dll path as none, as it couldn't find the library)

I PRed some minor changes that include type and default channel settings. After that, looks like ready to go.

**Comment by mayankchetan** [comment]
@dzalkind, I think this is good to merge

**Pull request merged**
