### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rafmudaf**
## Purpose
This pull request updates the included OpenFAST repo to add a fix for bugs in the Python interface. It should allow for WEIS to run OpenFAST simulations with output data passed back to the calling routines in-memory.

TODO:

- [ ] Update the OpenFAST input files generated by WEIS to OpenFAST v3.0 format

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
To test whether this code works, first the OpenFAST input files generated by WEIS must be updated to OpenFAST v3.0 format. Then, I modified `runFAST_pywrapper.py` forcing it to use the OpenFAST Python interface.

Since I have not yet completed updating the OpenFAST input files, this has not been fully tested.

## Checklist
- [ ] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by rafmudaf** [comment]
Whoa. Did I merge this?

**Comment by yonghoonlee** [comment]
@rafmudaf It seems that this pull request is already merged. Actually I already adapted synchronized your recent changes into my own WEIS fork. Are they need to be more reviewed before it is merged into the develop branch? If so, I think I also need to revert changes in my fork as well. Please let me know. Thank you.

**Comment by rafmudaf** [comment]
@yonghoonlee Yes this pull request was accidentally and incorrectly merged. On my computer, I pushed to the wrong remote via git and that had the effect of merging this pull request. To correct this, I've added revert-commits to the `develop` branch in the WISDEM/WEIS repo, and I've opened a new draft pull request (#122).

The changes in #122 move the OpenFAST version up to v3.0.0, but the files generated by WEIS are not yet compatible with that version.

**Comment by yonghoonlee** [comment]
@rafmudaf Thank you for clarifying. I will also apply reverts you made to my fork as well.

**Pull request merged**
