### PR TITLE
fix bug, now stats only from TStart

### PR DESCRIPTION
**Pull request by ptrbortolotti**
Fix bug where OF stats always started from time=0 s

## Purpose
Fix bug 

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by gbarter — COMMENTED** [review]
Does this work?  I don't see where this keyword argument is properly parsed when done this way.

**Comment by ptrbortolotti** [comment]
let me check because now I'm not sure anymore

**Comment by gbarter** [comment]
I think we need to just call this method explicitly:
https://github.com/WISDEM/WEIS/blob/develop/pCrunch/pCrunch/io/openfast.py#L45

The `trim_data` keyword was in the other constructor for doing the analysis.  For reading the data it looks like the method has to be called directly.

**Comment by ptrbortolotti** [comment]
you are very right @gbarter , I don't know how my tests originally looked fine, the problem is still there

**Comment by gbarter** [comment]
Let me know if I can help or if the changes that are needed are clear.

**Review by gbarter — APPROVED** [review]

**Comment by JakeNunemaker** [comment]
Good catch @gbarter. I thought there was a catch for `trim_data` kwarg in the `__init__` but that is for `LoadsAnalaysis`.

Is this working now? It looks like a good fix to me. Sorry I was in a bunch of meetings today so could only kinda follow along.

**Review by JakeNunemaker — APPROVED** [review]

**Comment by ptrbortolotti** [comment]
thank you both! it should work fine now!

**Pull request merged**
