### PR TITLE
B/we mode

### PR DESCRIPTION
**Pull request by ptrbortolotti**
Usual problem where a minor PR becomes a monster. In reality, this PR simply:
1) Updates wisdem to latest develop
2) Fixes a bug that imposed WE_Mode of ROSCO (the wind speed estimator) to be either 0 or 2. In reality, 1 is also a possibility (1 = Immersion and Invariance Estimator)
3) Fixes a bug in the writing out of the control design variables, which weren't placed in the yaml correctly (they followed the old control ontology)
4) Removes the geometry ontology default yaml file
5) Updates the sample batch script
6) Fixes a few bugs in the modeling options that appeared when DAC is turned on

### CODE REVIEW

**Review by gbarter — APPROVED** [review]

**Review by johnjasa — CHANGES_REQUESTED** [review]
These look good to me! Thanks for updating the Eagle script too, based on my questions.

Looks like the complete example suite just has two hopefully simple errors: https://github.com/WISDEM/WEIS/pull/50/checks?check_run_id=1624263382#step:7:3585

Let me if you want me to debug or check out anything.

**Comment by ptrbortolotti** [comment]
@johnjasa I think the error was generated by pCrunch trying to compute the DELs for the 1s simulations of the tests... tests are now passing locally. let's see what GitHub actions have to say

**Comment by ptrbortolotti** [comment]
@gbarter is the very latest commit right? I copied it from the wisdem glue_code. if all is right, @johnjasa we could probably merge

**Comment by gbarter** [comment]
Are you asking me a question?  Not sure I understand.

**Review by johnjasa — APPROVED** [review]

**Comment by ptrbortolotti** [comment]
by pulling the latest wisdem into weds, an error about G_soil was returned. I fixed it with this commit
https://github.com/WISDEM/WEIS/pull/50/commits/5aab9d84744a1cc0a3caf2324b7cdf3d72aeede9
copying how the environmental data is passed to towers within wisdem. tests now pass, but I'm always a little scared to touch the connections to towers_post and so I'd feel better if you could check them

**Comment by gbarter** [comment]
Looks good to me

**Pull request merged**
